"""Turn docs/enemy_database.txt into tools/EnemyDatabase.luau (ServerStorage.DevTools.EnemyDatabase).

The admin command validateEnemies compares Config/Enemies with this table (HP, DMG, Gold, loot item and type),
so the database text stays the single source of truth.

Usage:  python tools/gen_enemy_database.py
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "docs", "enemy_database.txt")
TARGET = os.path.join(ROOT, "tools", "EnemyDatabase.luau")

# Zones.List order (Config/Zones.luau)
ZONE_IDS = ["Plains", "Desert", "Jungle", "Tundra", "Swamp", "Volcano", "Hell", "Heaven", "Dead", "Abyss",
            "Mechanical", "Void"]
SUFFIX = {"": 1, "K": 1e3, "M": 1e6, "B": 1e9, "T": 1e12, "Qa": 1e15}
STAT_LINE = re.compile(
    r"\|\s*HP\s+([\d.]+)(Qa|[KMBT]?)\s*\|\s*DMG\s+([\d.]+)(Qa|[KMBT]?)\s*\|\s*COINS\s+([\d.]+)(Qa|[KMBT]?)\s*\|\s*LOOT:\s*(.+?)\s*\(([^)]*)\)\s*$")


def number(digits, suffix):
    return float(digits) * SUFFIX[suffix]


def make_id(zone_id, name):
    """Same rule as Config/Enemies makeId: lower case, apostrophes removed, other symbols -> "_"."""
    slug = name.lower().replace("'", "")
    slug = re.sub(r"[^0-9a-z]+", "_", slug)
    prefix = zone_id.lower() + "_"
    if slug.startswith(prefix):
        slug = slug[len(prefix):]
    return prefix + slug


def parse():
    entries = []
    zone = None
    sub_zone = 0
    pending = None  # (name, role) of a "MINI-BOSS n: Name" line whose stats are on the next line
    with open(SOURCE, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            header = re.match(r"\s*ZONE\s+(\d+):", line)
            if header:
                zone = ZONE_IDS[int(header.group(1)) - 1]
                sub_zone = 0
                continue
            sub = re.match(r"---\s*Sub-zone\s+(\d+)", line)
            if sub:
                sub_zone = int(sub.group(1))
                continue
            if zone is None:
                continue
            mini = re.match(r"\s*MINI-BOSS\s+\d+:\s*(.+?)\s*$", line)
            if mini and "|" not in line:
                pending = (mini.group(1), "MiniBoss")
                continue
            boss = re.match(r"\s*BOSS:\s*(.+?)\s*$", line)
            if boss and "|" not in line:
                pending = (boss.group(1), "Boss")
                continue
            if line.strip() and "|" not in line and not line.startswith(("=", "-", " ")):
                pending = (line.strip(), "Normal")  # a long name alone, its stats on the next line
                continue
            stats = STAT_LINE.search(line)
            if not stats:
                continue
            before = line[:stats.start()].strip()
            if before.startswith("BOSS:"):
                name, role = before[len("BOSS:"):].strip(), "Boss"
            elif before == "" and pending:
                name, role = pending
            else:
                name, role = before, "Normal"
            pending = None
            loot_type = stats.group(8).split(",")[0].strip()
            entries.append({
                "id": make_id(zone, name), "name": name, "zone": zone, "sub": sub_zone, "role": role,
                "hp": number(stats.group(1), stats.group(2)), "dmg": number(stats.group(3), stats.group(4)),
                "gold": number(stats.group(5), stats.group(6)), "loot": stats.group(7).strip(), "type": loot_type,
            })
    return entries


def luau_number(value):
    return str(int(value)) if value == int(value) else repr(value)


def write(entries):
    lines = [
        "--!strict",
        "-- GENERATED by tools/gen_enemy_database.py from docs/enemy_database.txt - do not edit by hand.",
        "-- [id] = { HP, DMG, Gold, loot item, loot type } (values as written in the file, 3 significant digits)",
        "return {",
    ]
    for e in entries:
        lines.append(
            f'\t{e["id"]} = {{ {luau_number(e["hp"])}, {luau_number(e["dmg"])}, {luau_number(e["gold"])}, '
            f'"{e["loot"]}", "{e["type"]}" }},')
    lines.append("}")
    with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    data = parse()
    write(data)
    per_zone = {}
    for e in data:
        per_zone[e["zone"]] = per_zone.get(e["zone"], 0) + 1
    print(f"{len(data)} enemies written to {os.path.relpath(TARGET, ROOT)}: {per_zone}")
